# manifest:
#   remotes:
#    - name: zmkfirmware
#      url-base: https://github.com/zmkfirmware
#    - name: zmk-config-hillside
#      url-base: https://github.com/rossw42
#   projects:
#     - name: zmk
#       remote: zmkfirmware
#       revision: main
#       import: app/west.yml
#     - name: zmk-config-hillside
#       remote: zmk-config-hillside
#       revision: main
#   self:
#     path: config


manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # - name: zmk-config-hillside
    #   url-base: https://github.com/rossw42
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2.1
      import: app/west.yml
  self:
    path: config
